services:
  - type: web
    name: wanderlust
    runtime: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: CLOUD_NAME
        sync: false
      - key: CLOUD_API_KEY
        sync: false
      - key: CLOUD_API_SECRET
        sync: false
      - key: ATLASTDB_URL
        sync: false
      - key: SECRET
        sync: false
