services:
  - type: web
    name: wanderlust
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: ATLASTDB_URL
        sync: false
      - key: PORT
        value: 3000
